// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: crypto/crypto.proto

package crypto

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PubKey struct {
	// Types that are valid to be assigned to PubKey:
	//	*PubKey_Ed25519
	//	*PubKey_Sr25519
	//	*PubKey_Secp256K1
	PubKey               isPubKey_PubKey `protobuf_oneof:"pub_key"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PubKey) Reset()         { *m = PubKey{} }
func (m *PubKey) String() string { return proto.CompactTextString(m) }
func (*PubKey) ProtoMessage()    {}
func (*PubKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_27e1fe69dc202ca1, []int{0}
}
func (m *PubKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubKey.Unmarshal(m, b)
}
func (m *PubKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubKey.Marshal(b, m, deterministic)
}
func (m *PubKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubKey.Merge(m, src)
}
func (m *PubKey) XXX_Size() int {
	return xxx_messageInfo_PubKey.Size(m)
}
func (m *PubKey) XXX_DiscardUnknown() {
	xxx_messageInfo_PubKey.DiscardUnknown(m)
}

var xxx_messageInfo_PubKey proto.InternalMessageInfo

type isPubKey_PubKey interface {
	isPubKey_PubKey()
}

type PubKey_Ed25519 struct {
	Ed25519 []byte `protobuf:"bytes,1,opt,name=ed25519,proto3,oneof" json:"ed25519,omitempty"`
}
type PubKey_Sr25519 struct {
	Sr25519 []byte `protobuf:"bytes,2,opt,name=sr25519,proto3,oneof" json:"sr25519,omitempty"`
}
type PubKey_Secp256K1 struct {
	Secp256K1 []byte `protobuf:"bytes,3,opt,name=secp256k1,proto3,oneof" json:"secp256k1,omitempty"`
}

func (*PubKey_Ed25519) isPubKey_PubKey()   {}
func (*PubKey_Sr25519) isPubKey_PubKey()   {}
func (*PubKey_Secp256K1) isPubKey_PubKey() {}

func (m *PubKey) GetPubKey() isPubKey_PubKey {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *PubKey) GetEd25519() []byte {
	if x, ok := m.GetPubKey().(*PubKey_Ed25519); ok {
		return x.Ed25519
	}
	return nil
}

func (m *PubKey) GetSr25519() []byte {
	if x, ok := m.GetPubKey().(*PubKey_Sr25519); ok {
		return x.Sr25519
	}
	return nil
}

func (m *PubKey) GetSecp256K1() []byte {
	if x, ok := m.GetPubKey().(*PubKey_Secp256K1); ok {
		return x.Secp256K1
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PubKey) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PubKey_Ed25519)(nil),
		(*PubKey_Sr25519)(nil),
		(*PubKey_Secp256K1)(nil),
	}
}

type PrivKey struct {
	// Types that are valid to be assigned to PrivKey:
	//	*PrivKey_Ed25519
	//	*PrivKey_Sr25519
	//	*PrivKey_Secp256K1
	PrivKey              isPrivKey_PrivKey `protobuf_oneof:"priv_key"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PrivKey) Reset()         { *m = PrivKey{} }
func (m *PrivKey) String() string { return proto.CompactTextString(m) }
func (*PrivKey) ProtoMessage()    {}
func (*PrivKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_27e1fe69dc202ca1, []int{1}
}
func (m *PrivKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivKey.Unmarshal(m, b)
}
func (m *PrivKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivKey.Marshal(b, m, deterministic)
}
func (m *PrivKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivKey.Merge(m, src)
}
func (m *PrivKey) XXX_Size() int {
	return xxx_messageInfo_PrivKey.Size(m)
}
func (m *PrivKey) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivKey.DiscardUnknown(m)
}

var xxx_messageInfo_PrivKey proto.InternalMessageInfo

type isPrivKey_PrivKey interface {
	isPrivKey_PrivKey()
}

type PrivKey_Ed25519 struct {
	Ed25519 []byte `protobuf:"bytes,1,opt,name=ed25519,proto3,oneof" json:"ed25519,omitempty"`
}
type PrivKey_Sr25519 struct {
	Sr25519 []byte `protobuf:"bytes,2,opt,name=sr25519,proto3,oneof" json:"sr25519,omitempty"`
}
type PrivKey_Secp256K1 struct {
	Secp256K1 []byte `protobuf:"bytes,3,opt,name=secp256k1,proto3,oneof" json:"secp256k1,omitempty"`
}

func (*PrivKey_Ed25519) isPrivKey_PrivKey()   {}
func (*PrivKey_Sr25519) isPrivKey_PrivKey()   {}
func (*PrivKey_Secp256K1) isPrivKey_PrivKey() {}

func (m *PrivKey) GetPrivKey() isPrivKey_PrivKey {
	if m != nil {
		return m.PrivKey
	}
	return nil
}

func (m *PrivKey) GetEd25519() []byte {
	if x, ok := m.GetPrivKey().(*PrivKey_Ed25519); ok {
		return x.Ed25519
	}
	return nil
}

func (m *PrivKey) GetSr25519() []byte {
	if x, ok := m.GetPrivKey().(*PrivKey_Sr25519); ok {
		return x.Sr25519
	}
	return nil
}

func (m *PrivKey) GetSecp256K1() []byte {
	if x, ok := m.GetPrivKey().(*PrivKey_Secp256K1); ok {
		return x.Secp256K1
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PrivKey) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PrivKey_Ed25519)(nil),
		(*PrivKey_Sr25519)(nil),
		(*PrivKey_Secp256K1)(nil),
	}
}

func init() {
	proto.RegisterType((*PubKey)(nil), "tendermint.crypto.crypto.PubKey")
	proto.RegisterType((*PrivKey)(nil), "tendermint.crypto.crypto.PrivKey")
}

func init() { proto.RegisterFile("crypto/crypto.proto", fileDescriptor_27e1fe69dc202ca1) }

var fileDescriptor_27e1fe69dc202ca1 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x2e, 0xaa, 0x2c,
	0x28, 0xc9, 0xd7, 0x87, 0x50, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x12, 0x25, 0xa9, 0x79,
	0x29, 0xa9, 0x45, 0xb9, 0x99, 0x79, 0x25, 0x7a, 0x50, 0x09, 0x08, 0xa5, 0x94, 0xcd, 0xc5, 0x16,
	0x50, 0x9a, 0xe4, 0x9d, 0x5a, 0x29, 0x24, 0xc5, 0xc5, 0x9e, 0x9a, 0x62, 0x64, 0x6a, 0x6a, 0x68,
	0x29, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0xe3, 0xc1, 0x10, 0x04, 0x13, 0x00, 0xc9, 0x15, 0x17, 0x41,
	0xe4, 0x98, 0x60, 0x72, 0x50, 0x01, 0x21, 0x39, 0x2e, 0xce, 0xe2, 0xd4, 0xe4, 0x02, 0x23, 0x53,
	0xb3, 0x6c, 0x43, 0x09, 0x66, 0xa8, 0x2c, 0x42, 0xc8, 0x89, 0x93, 0x8b, 0xbd, 0xa0, 0x34, 0x29,
	0x3e, 0x3b, 0xb5, 0x52, 0x29, 0x97, 0x8b, 0x3d, 0xa0, 0x28, 0xb3, 0x8c, 0x96, 0xb6, 0x71, 0x71,
	0x71, 0x14, 0x14, 0x65, 0x96, 0x81, 0xac, 0x73, 0xd2, 0x8c, 0x52, 0x4f, 0xcf, 0x2c, 0xc9, 0x28,
	0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x47, 0x04, 0x01, 0x32, 0x13, 0x12, 0x0c, 0x49, 0x6c, 0xe0,
	0x70, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x2d, 0xf8, 0x99, 0x29, 0x3e, 0x01, 0x00, 0x00,
}
